FROM node:18-alpine

WORKDIR /app

# Copier les fichiers de dépendances
COPY package*.json ./

# Installer toutes les dépendances (y compris dev)
RUN npm install

# Copier le reste du code
COPY . .

# Exposer le port de développement
EXPOSE 3000

# Lancer le serveur de développement
CMD ["npm", "start"]
